listen_addresses = '*'
max_connections = 32
shared_buffers = '32MB'
work_mem = '1MB'
max_parallel_workers = 0
track_commit_timestamp = on
wal_level = replica
archive_mode = on
archive_timeout = '120s'
max_wal_size = '256MB'
archive_command = 'test $(du -sk /capacity-wal | cut -f1) -lt 1048576 && test ! -f /capacity-wal/%f && cp %p /capacity-wal/%f'
logging_collector = off
log_statement = 'none'
