name: coolify-proxy
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: "traefik:v3.7.14@sha256:e849695bc5c317da0cec22bfee4794fd9e15871fe554f864d31b625983e883ff"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - coolify
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    healthcheck:
      test: "wget -qO- http://localhost:80/ping || exit 1"
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/data/coolify/proxy/:/traefik"
    command:
      - "--ping=true"
      - "--ping.entrypoint=http"
      - "--api=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.http.http.encodequerysemicolons=true"
      - "--entryPoints.http.http2.maxConcurrentStreams=250"
      - "--entrypoints.https.http.encodequerysemicolons=true"
      - "--entryPoints.https.http2.maxConcurrentStreams=250"
      - "--entrypoints.https.http3"
      - "--providers.file.directory=/traefik/dynamic/"
      - "--providers.file.watch=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    labels:
      - traefik.enable=false
      - coolify.managed=true
      - coolify.proxy=true
