ARG POSTGRES_IMAGE=postgres:18.6-bookworm@sha256:9e73daeb439141c2b11eea2463f5f1a3b269fd90d897b41cddb7cb440f21aa5d
FROM ${POSTGRES_IMAGE}
COPY --chmod=0755 age rclone /usr/local/bin/
RUN age --version && rclone version && mkdir /capacity-wal && chown postgres:postgres /capacity-wal
