ARG BACKUP_IMAGE=backup
FROM postgres:18.6-bookworm@sha256:9551dd5bf356409a21b31248f49b33bba9bb1877365f3a7e933aecd9af3cf52d AS build
RUN apt-get update && apt-get install --no-install-recommends -y \
    postgresql-server-dev-18=18.6-1.pgdg12+2 build-essential=12.9 \
    libcurl4-openssl-dev=7.88.1-10+deb12u15 uuid-dev=2.38.1-5+deb12u3 \
    libssl-dev=3.0.20-1~deb12u2 libssl3=3.0.20-1~deb12u2 \
    liblz4-dev=1.9.4-1 libzstd-dev=1.5.4+dfsg2-5 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /extension
COPY pg_clickhouse/ ./
RUN test "$(/usr/lib/postgresql/18/bin/pg_config --version)" = "PostgreSQL 18.6 (Debian 18.6-1.pgdg12+2)" \
    && make -j2 PG_CONFIG=/usr/lib/postgresql/18/bin/pg_config \
    && make install DESTDIR=/output PG_CONFIG=/usr/lib/postgresql/18/bin/pg_config \
    && dpkg-query -W > /output/build-packages.txt \
    && ldd pg_clickhouse.so
FROM ${BACKUP_IMAGE}
RUN apt-get update && apt-get install --no-install-recommends -y \
    libcurl4=7.88.1-10+deb12u15 libuuid1=2.38.1-5+deb12u3 \
    libssl3=3.0.20-1~deb12u2 liblz4-1=1.9.4-1 libzstd1=1.5.4+dfsg2-5 \
    && rm -rf /var/lib/apt/lists/*
COPY --from=build /output/usr/lib/postgresql/18/lib/pg_clickhouse.so /usr/lib/postgresql/18/lib/
COPY --from=build /output/usr/share/postgresql/18/extension/pg_clickhouse* /usr/share/postgresql/18/extension/
COPY --from=build /output/build-packages.txt /usr/local/share/pg-clickhouse-build-packages.txt
RUN ldd /usr/lib/postgresql/18/lib/pg_clickhouse.so \
    && ! ldd /usr/lib/postgresql/18/lib/pg_clickhouse.so | grep 'not found' \
    && dpkg-query -W > /usr/local/share/pg-clickhouse-runtime-packages.txt
LABEL org.opencontainers.image.source="https://github.com/ClickHouse/pg_clickhouse" \
      org.opencontainers.image.revision="6ee116efa554c3e39705e2abff776069fef412eb" \
      org.opencontainers.image.version="0.10.0"
