ARG POSTGRES_IMAGE=postgres:18.6-bookworm@sha256:9551dd5bf356409a21b31248f49b33bba9bb1877365f3a7e933aecd9af3cf52d
FROM ${POSTGRES_IMAGE}
COPY --chmod=0755 age rclone /usr/local/bin/
RUN age --version && rclone version && mkdir /capacity-wal && chown postgres:postgres /capacity-wal
